### ISSUE TITLE
duplicate usage text

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/boatswain#4]
hey @bpmweel, great job on this tool. I had a minor issue with the help/usage text, since both ``boatswain clean`` and ``boatswain push`` have the same description (see text below). I'm guessing that's a left over from copy-pasting some boilerplate?

BTW I installed from pip, not sure about the version.
BTW we're using boatswain here https://github.com/NLeSC/xenon-docker-images

```text
 boatswain -h
usage: boatswain [-h] {build,clean,push,tree} ...

Builds docker images based on a docker-compose style yaml file

positional arguments:
  {build,clean,push,tree}
                        sub-command help
    build               builds the images specified in the boatswain.yml file
    clean               Clean the images specified in the boatswain.yml file
    push                Clean the images specified in the boatswain.yml file
    tree                Print the tree of the boatswain.yml file

optional arguments:
  -h, --help            show this help message and exit

```

**Comment by bpmweel** [comment]
Thanks for this. Fixed in the next release
